/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __nad_lcm_obstacle_info_hpp__
#define __nad_lcm_obstacle_info_hpp__

#include <vector>
#include "nad_obstacle.hpp"

namespace nad_lcm
{

class obstacle_info
{
public:
    int16_t    num_of_obstacle;

    std::vector< nad_lcm::nad_obstacle > obu_obstacle;

public:
    /**
     * Encode a message into binary form.
     *
     * @param buf The output buffer.
     * @param offset Encoding starts at thie byte offset into @p buf.
     * @param maxlen Maximum number of bytes to write.  This should generally be
     *  equal to getEncodedSize().
     * @return The number of bytes encoded, or <0 on error.
     */
    inline int encode(void *buf, int offset, int maxlen) const;

    /**
     * Check how many bytes are required to encode this message.
     */
    inline int getEncodedSize() const;

    /**
     * Decode a message from binary form into this instance.
     *
     * @param buf The buffer containing the encoded message.
     * @param offset The byte offset into @p buf where the encoded message starts.
     * @param maxlen The maximum number of bytes to reqad while decoding.
     * @return The number of bytes decoded, or <0 if an error occured.
     */
    inline int decode(const void *buf, int offset, int maxlen);

    /**
     * Retrieve the 64-bit fingerprint identifying the structure of the message.
     * Note that the fingerprint is the same for all instances of the same
     * message type, and is a fingerprint on the message type definition, not on
     * the message contents.
     */
    inline static int64_t getHash();

    /**
     * Returns "obstacle_info"
     */
    inline static const char* getTypeName();

    // LCM support functions. Users should not call these
    inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
    inline int _getEncodedSizeNoHash() const;
    inline int _decodeNoHash(const void *buf, int offset, int maxlen);
    inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int obstacle_info::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen;
    else pos += tlen;

    return pos;
}

int obstacle_info::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen;
    else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen;
    else pos += thislen;

    return pos;
}

int obstacle_info::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t obstacle_info::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* obstacle_info::getTypeName()
{
    return "obstacle_info";
}

int obstacle_info::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_obstacle, 1);
    if(tlen < 0) return tlen;
    else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_obstacle; a0++)
    {
        tlen = this->obu_obstacle[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen;
        else pos += tlen;
    }

    return pos;
}

int obstacle_info::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_obstacle, 1);
    if(tlen < 0) return tlen;
    else pos += tlen;

    this->obu_obstacle.resize(this->num_of_obstacle);
    for (int a0 = 0; a0 < this->num_of_obstacle; a0++)
    {
        tlen = this->obu_obstacle[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen;
        else pos += tlen;
    }

    return pos;
}

int obstacle_info::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_obstacle; a0++)
    {
        enc_size += this->obu_obstacle[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t obstacle_info::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == obstacle_info::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)obstacle_info::getHash };

    uint64_t hash = 0x73639e6f0a4f6c67LL +
                    nad_lcm::nad_obstacle::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
