/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __obu_lcm_rect_t_hpp__
#define __obu_lcm_rect_t_hpp__

#include "point_t.hpp"

namespace obu_lcm
{

/// ¾ØÐÎ
class rect_t
{
public:
    obu_lcm::point_t p1;

    obu_lcm::point_t p2;

    obu_lcm::point_t p3;

    obu_lcm::point_t p4;

public:
    /**
     * Encode a message into binary form.
     *
     * @param buf The output buffer.
     * @param offset Encoding starts at thie byte offset into @p buf.
     * @param maxlen Maximum number of bytes to write.  This should generally be
     *  equal to getEncodedSize().
     * @return The number of bytes encoded, or <0 on error.
     */
    inline int encode(void *buf, int offset, int maxlen) const;

    /**
     * Check how many bytes are required to encode this message.
     */
    inline int getEncodedSize() const;

    /**
     * Decode a message from binary form into this instance.
     *
     * @param buf The buffer containing the encoded message.
     * @param offset The byte offset into @p buf where the encoded message starts.
     * @param maxlen The maximum number of bytes to reqad while decoding.
     * @return The number of bytes decoded, or <0 if an error occured.
     */
    inline int decode(const void *buf, int offset, int maxlen);

    /**
     * Retrieve the 64-bit fingerprint identifying the structure of the message.
     * Note that the fingerprint is the same for all instances of the same
     * message type, and is a fingerprint on the message type definition, not on
     * the message contents.
     */
    inline static int64_t getHash();

    /**
     * Returns "rect_t"
     */
    inline static const char* getTypeName();

    // LCM support functions. Users should not call these
    inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
    inline int _getEncodedSizeNoHash() const;
    inline int _decodeNoHash(const void *buf, int offset, int maxlen);
    inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int rect_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen;
    else pos += tlen;

    return pos;
}

int rect_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen;
    else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen;
    else pos += thislen;

    return pos;
}

int rect_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t rect_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* rect_t::getTypeName()
{
    return "rect_t";
}

int rect_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->p1._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->p2._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->p3._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->p4._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    return pos;
}

int rect_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->p1._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->p2._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->p3._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    tlen = this->p4._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen;
    else pos += tlen;

    return pos;
}

int rect_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->p1._getEncodedSizeNoHash();
    enc_size += this->p2._getEncodedSizeNoHash();
    enc_size += this->p3._getEncodedSizeNoHash();
    enc_size += this->p4._getEncodedSizeNoHash();
    return enc_size;
}

int64_t rect_t::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == rect_t::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)rect_t::getHash };

    int64_t hash = 0xf8af6affb121761fLL +
                   obu_lcm::point_t::_computeHash(&cp) +
                   obu_lcm::point_t::_computeHash(&cp) +
                   obu_lcm::point_t::_computeHash(&cp) +
                   obu_lcm::point_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
